//
//  CMPComapiFoundation.h
//  CMPComapiFoundation
//
//  Created by Dominik Kowalski on 14/08/2018.
//  Copyright © 2018 Comapi. All rights reserved.
//

#import <Foundation/Foundation.h>

//! Project version number for CMPComapiFoundation.
FOUNDATION_EXPORT double CMPComapiFoundationVersionNumber;

//! Project version string for CMPComapiFoundation.
FOUNDATION_EXPORT const unsigned char CMPComapiFoundationVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <CMPComapiFoundation/PublicHeader.h>


#import "CMPComapiFoundation.h"
#import "CMPComapiClient.h"
#import "CMPComapi.h"
#import "CMPAPIConfiguration.h"
#import "CMPComapiConfig.h"
#import "CMPLogConfig.h"
#import "CMPConstants.h"
#import "CMPErrors.h"
#import "CMPLog.h"
#import "CMPLogger.h"
#import "CMPLogLevel.h"
#import "CMPFileDestination.h"
#import "CMPLoggingDestination.h"
#import "CMPXcodeConsoleDestination.h"
#import "CMPAuthenticationDelegate.h"
#import "CMPHTTPHeader.h"
#import "CMPJSONConstructable.h"
#import "CMPJSONDecoding.h"
#import "CMPJSONEncoding.h"
#import "CMPJSONRepresentable.h"
#import "CMPRequestManager.h"
#import "CMPRequestPerformer.h"
#import "CMPRequestPerforming.h"
#import "CMPBaseService.h"
#import "CMPServices.h"
#import "CMPMessagingService.h"
#import "CMPProfileService.h"
#import "CMPSessionService.h"
#import "CMPAuthChallengeHandler.h"
#import "CMPSessionAuthProvider.h"
#import "CMPSessionManager.h"
#import "CMPEventParser.h"
#import "CMPEvent.h"
#import "CMPConversationEvents.h"
#import "CMPConversationMessageEvents.h"
#import "CMPProfileEvents.h"
#import "CMPSocketEvents.h"
#import "CMPAddConversationTemplate.h"
#import "CMPAddParticipantsTemplate.h"
#import "CMPContentUploadTemplate.h"
#import "CMPDeleteConversationTemplate.h"
#import "CMPEventQueryTemplate.h"
#import "CMPGetConversationsTemplate.h"
#import "CMPGetConversationTemplate.h"
#import "CMPGetMessagesTemplate.h"
#import "CMPGetParticipantsTemplate.h"
#import "CMPRemoveParticipantsTemplate.h"
#import "CMPSendMessagesTemplate.h"
#import "CMPSendStatusUpdateTemplate.h"
#import "CMPUpdateConversationTemplate.h"
#import "CMPContentData.h"
#import "CMPContentUploadResult.h"
#import "CMPConversation.h"
#import "CMPConversationParticipant.h"
#import "CMPConversationScope.h"
#import "CMPConversationUpdate.h"
#import "CMPGetMessagesResult.h"
#import "CMPMessage.h"
#import "CMPMessageAlert.h"
#import "CMPMessageAlertPlatforms.h"
#import "CMPMessageContext.h"
#import "CMPMessageDeliveryStatus.h"
#import "CMPMessagePart.h"
#import "CMPMessageParticipant.h"
#import "CMPMessageStatus.h"
#import "CMPMessageStatusUpdate.h"
#import "CMPNewConversation.h"
#import "CMPOrphanedEvent.h"
#import "CMPRoleAttributes.h"
#import "CMPRoles.h"
#import "CMPSendableMessage.h"
#import "CMPSendMessagesResult.h"
#import "CMPGetProfileTemplate.h"
#import "CMPPatchProfileTemplate.h"
#import "CMPQueryProfilesTemplate.h"
#import "CMPUpdateProfileTemplate.h"
#import "CMPProfile.h"
#import "CMPQueryBuilder.h"
#import "CMPSetAPNSDetailsTemplate.h"
#import "CMPAPNSDetails.h"
#import "CMPAPNSDetailsBody.h"
#import "CMPHTTPRequestTemplate.h"
#import "CMPRequestTemplate.h"
#import "CMPResult.h"
#import "CMPAuthorizeSessionTemplate.h"
#import "CMPDeleteSessionTemplate.h"
#import "CMPStartNewSessionTemplate.h"
#import "CMPAuthenticationChallenge.h"
#import "CMPAuthorizeSessionBody.h"
#import "CMPSession.h"
#import "CMPSessionAuth.h"
#import "CMPSocketTemplate.h"
#import "CMPURLResult.h"
#import "CMPBroadcastDelegate.h"
#import "CMPSocketManager.h"
#import "CMPKeychain.h"
#import "CMPUtilities.h"
#import "NSData+CMPUtility.h"
#import "NSDate+CMPUtility.h"
#import "NSDateFormatter+CMPUtility.h"
#import "NSString+CMPUtility.h"
#import "NSURLRequest+CMPUtility.h"
#import "NSURLResponse+CMPUtility.h"




